name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    with:
      push: true
      artifact: ''
      helmDir: 'helm'
  helm-event:
    uses: onecx/ci-product/.github/workflows/helm-send-event.yml@v1
    needs: helm
    secrets: inherit
    with:
      targetRepository: onecx/onecx-k8s