name: Build Pull Request
on:
  pull_request:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    with:
      helmDir: 'helm'
      artifact: ''